[platformio]
default_envs = pilot

; ============================================================
; Common settings for both environments
; ============================================================
[common]
platform = espressif32@^6.7.0
board = esp32dev
framework = arduino
build_flags = -DLWIP_MAX_SOCKETS=16
upload_speed = 921600
monitor_speed = 115200

; ============================================================
; PILOT environment
; ESP32 #1 — near the pilot, reads CRSF from radio, sends UDP
;
; Go: GOOS=linux GOARCH=arm go build -o pilot ./cmd/pilot
; C++: pio run -e pilot -t upload
; ============================================================
[env:pilot]
extends = common
build_src_filter = +<*> -<.git/> -<drone/>

; ============================================================
; DRONE environment
; ESP32 #2 — near the drone, receives UDP, sends CRSF to JR module
;
; Go: GOOS=linux GOARCH=arm go build -o drone ./cmd/drone
; C++: pio run -e drone -t upload
; ============================================================
[env:drone]
extends = common
build_src_filter = +<*> -<.git/> -<pilot/>
