[platformio]
default_envs = pilot

[env]
platform       = espressif32
board          = esp32dev
framework      = arduino
monitor_speed  = 115200
upload_speed   = 921600
build_flags    = -DCORE_DEBUG_LEVEL=0

[env:pilot]
build_src_filter = +<pilot/>
build_flags      = -DROLE_PILOT

[env:drone]
build_src_filter = +<drone/>
build_flags      = -DROLE_DRONE
